// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6WWZG8KrQH6vfiz8vN3NH14bX6gQSpu8',
    appId: '1:315384652986:web:9351f9a335beb7ed39ce83',
    messagingSenderId: '315384652986',
    projectId: 'tortee-60675',
    authDomain: 'tortee-60675.firebaseapp.com',
    storageBucket: 'tortee-60675.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeuJ3E4bHuAmv6EUufFSOFzphfmJSbjX0',
    appId: '1:315384652986:android:bf6b73af6353c44539ce83',
    messagingSenderId: '315384652986',
    projectId: 'tortee-60675',
    storageBucket: 'tortee-60675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkDgf7vQguURXenVvJzvySEr4EuNkE-tQ',
    appId: '1:315384652986:ios:917317c7be176cab39ce83',
    messagingSenderId: '315384652986',
    projectId: 'tortee-60675',
    storageBucket: 'tortee-60675.appspot.com',
    iosBundleId: 'com.example.tortee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkDgf7vQguURXenVvJzvySEr4EuNkE-tQ',
    appId: '1:315384652986:ios:917317c7be176cab39ce83',
    messagingSenderId: '315384652986',
    projectId: 'tortee-60675',
    storageBucket: 'tortee-60675.appspot.com',
    iosBundleId: 'com.example.tortee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6WWZG8KrQH6vfiz8vN3NH14bX6gQSpu8',
    appId: '1:315384652986:web:9cdf33e598f3f8cd39ce83',
    messagingSenderId: '315384652986',
    projectId: 'tortee-60675',
    authDomain: 'tortee-60675.firebaseapp.com',
    storageBucket: 'tortee-60675.appspot.com',
  );
}
